name: Build FortiusANT

on: [push]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Build Windows Executables
      shell: cmd
      run: |
        ci/windows/build.bat
    - uses: actions/upload-artifact@v2
      with:
        name: Artifacts
        path: |
          pythoncode\dist\FortiusANT.exe
          pythoncode\dist\ExplorANT.exe

  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Build macOS Executable
      run: |
        ci/macos/build
    - uses: actions/upload-artifact@v2
      with:
        name: Artifacts
        path: |
          pythoncode\dist\FortiusANT.app
